#!/usr/bin/env bash
# Sync docs/wiki/ to the GitHub Wiki repo (https://github.com/Hesper-Labs/leakshield.wiki.git).
#
# Usage:
#   bash scripts/sync-wiki.sh
#
# The wiki repo is a separate git repo on github.com that GitHub initialises after the first
# page is created via the web UI. If the clone fails with "Repository not found", visit
# https://github.com/Hesper-Labs/leakshield/wiki and create any placeholder page first; then
# rerun.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_ROOT/docs/wiki"
WORK="$(mktemp -d -t leakshield-wiki.XXXXXX)"
WIKI_URL="${LEAKSHIELD_WIKI_URL:-https://github.com/Hesper-Labs/leakshield.wiki.git}"

cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

git clone --quiet "$WIKI_URL" "$WORK"
rm -f "$WORK"/*.md
cp "$SRC"/*.md "$WORK"/

cd "$WORK"
if [[ -z "$(git status --porcelain)" ]]; then
  echo "wiki: no changes"
  exit 0
fi
git add .
git commit -m "sync wiki from docs/wiki/

Generated by scripts/sync-wiki.sh from main."
git push origin HEAD

echo "wiki: pushed"
