# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inspector_pb2 as inspector__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inspector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InspectorStub(object):
    """Inspector is the gRPC service that decides DLP outcomes for prompts.
    The gateway calls Inspector for every request before forwarding to a
    provider.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InspectPrompt = channel.unary_unary(
                '/leakshield.inspector.v1.Inspector/InspectPrompt',
                request_serializer=inspector__pb2.InspectRequest.SerializeToString,
                response_deserializer=inspector__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.InspectStreamWindow = channel.stream_stream(
                '/leakshield.inspector.v1.Inspector/InspectStreamWindow',
                request_serializer=inspector__pb2.WindowChunk.SerializeToString,
                response_deserializer=inspector__pb2.WindowDecision.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/leakshield.inspector.v1.Inspector/Health',
                request_serializer=inspector__pb2.HealthRequest.SerializeToString,
                response_deserializer=inspector__pb2.HealthResponse.FromString,
                _registered_method=True)


class InspectorServicer(object):
    """Inspector is the gRPC service that decides DLP outcomes for prompts.
    The gateway calls Inspector for every request before forwarding to a
    provider.
    """

    def InspectPrompt(self, request, context):
        """InspectPrompt makes a pre-flight DLP decision for a single prompt.
        It is invoked BEFORE the gateway opens an upstream provider connection;
        call it as a low-latency blocking RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectStreamWindow(self, request_iterator, context):
        """InspectStreamWindow continuously inspects chunks of a streamed
        response. Used when output filtering is enabled for a tenant.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health reports whether the inspector backend (Ollama, vLLM, etc.) is
        reachable and warm.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InspectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InspectPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectPrompt,
                    request_deserializer=inspector__pb2.InspectRequest.FromString,
                    response_serializer=inspector__pb2.InspectResponse.SerializeToString,
            ),
            'InspectStreamWindow': grpc.stream_stream_rpc_method_handler(
                    servicer.InspectStreamWindow,
                    request_deserializer=inspector__pb2.WindowChunk.FromString,
                    response_serializer=inspector__pb2.WindowDecision.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=inspector__pb2.HealthRequest.FromString,
                    response_serializer=inspector__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leakshield.inspector.v1.Inspector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('leakshield.inspector.v1.Inspector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inspector(object):
    """Inspector is the gRPC service that decides DLP outcomes for prompts.
    The gateway calls Inspector for every request before forwarding to a
    provider.
    """

    @staticmethod
    def InspectPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leakshield.inspector.v1.Inspector/InspectPrompt',
            inspector__pb2.InspectRequest.SerializeToString,
            inspector__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectStreamWindow(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/leakshield.inspector.v1.Inspector/InspectStreamWindow',
            inspector__pb2.WindowChunk.SerializeToString,
            inspector__pb2.WindowDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leakshield.inspector.v1.Inspector/Health',
            inspector__pb2.HealthRequest.SerializeToString,
            inspector__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
